
services:
  nginx:
    image: nginx:latest
    container_name: myapp-nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
    container_name: myapp-backend
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

  mysql:
    image: mysql:8
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: myapp-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
